services:
  postgres:
    image: postgres:16-alpine
    container_name: ecommerce_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapiecommerce
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce_network

  redis:
    image: redis:7-alpine
    container_name: ecommerce_redis
    ports:
      - "6371:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce_network

  migrate:
    build: .
    command: alembic upgrade head
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/fastapiecommerce
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: ${SECRET_KEY:-c6e19f1e9a21069399f1ec8a8793db29aa086a7e8e0dc60319fcf9df9ce061a8}
      ACCESS_TOKEN_EXPIRE_MINUTES: 15
      REFRESH_TOKEN_EXPIRE_DAYS: 7
      UPLOAD_DIRECTORY: static/images
      MAX_IMAGE_SIZE: 10485760
      BIAS_FACTOR: 1.5
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
    networks:
      - ecommerce_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/fastapiecommerce
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: ${SECRET_KEY:-c6e19f1e9a21069399f1ec8a8793db29aa086a7e8e0dc60319fcf9df9ce061a8}
      ACCESS_TOKEN_EXPIRE_MINUTES: 15
      REFRESH_TOKEN_EXPIRE_DAYS: 7
      UPLOAD_DIRECTORY: static/images
      MAX_IMAGE_SIZE: 10485760
      BIAS_FACTOR: 1.5
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    volumes:
      - static:/app/app/static
    networks:
      - ecommerce_network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce_celery
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/fastapiecommerce
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: ${SECRET_KEY:-c6e19f1e9a21069399f1ec8a8793db29aa086a7e8e0dc60319fcf9df9ce061a8}
      ACCESS_TOKEN_EXPIRE_MINUTES: 15
      REFRESH_TOKEN_EXPIRE_DAYS: 7
      UPLOAD_DIRECTORY: static/images
      MAX_IMAGE_SIZE: 10485760
      BIAS_FACTOR: 1.5
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    command: celery -A app.core.celery worker --loglevel=info
    networks:
      - ecommerce_network

volumes:
  postgres_data:
  redis_data:
  static:

networks:
  ecommerce_network:
    driver: bridge
